### ISSUE TITLE
add next / previous buttons to bin page

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#103]
when viewing the bin landing page there should be buttons to navigate to next and previous bins.

**Comment by mike-kaimika** [comment]
Making note that this should wait until the combined page. I believe a lot of the logic on that page is based on a template variable for the bin that's passed in, which makes it more difficulty to change dynamically from the UI. The dataset page already handles this appropriately, and so that logic will get ported to the new page already
