### ISSUE TITLE
mosaic paging control "next" is disabled sometimes

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#199]
so far I can reproduce this by setting the scaling percent to 66%

**Comment by mike-kaimika** [comment]
@joefutrelle I think the issue is actually that the container around the options dropdown on the right side was set to 50%, so it covered the paging. Which means next, and if large enough, some of the page numbers were there but non clickable. I pushed up a fix; let me know if you can still reproduce the original issue

**Comment by joefutrelle** [comment]
Seems to work.
