### ISSUE TITLE
UI for navigating to specific ROI number

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#203]

**Comment by joefutrelle** [comment]
Typing the number in with validation that there is a ROI with that number.

**Comment by mike-kaimika** [comment]
@joefutrelle This would just be on the image page, right?

**Comment by joefutrelle** [comment]
It should go on the combined page (could be a modal) and also on the image page. Once you select an image (on either of those pages) it should take you to the image page.

I think validation could be done upon attempting to navigate, otherwise I'd have to deliver a list of image numbers to you up front, and that would generate more file system access on the backend which I'm trying to cut down on.

**Comment by joefutrelle** [comment]
I added the `list_images` API endpoint to assist with this

**Comment by mike-kaimika** [comment]
I committed a first draft of this to the dev branch. If the UI and functionality works, we'll need one small fix which is that the image from the mosaic in preview ALWAYS loads above the mosaic now, vs before when it could sometimes appear on the right when it fit

Otherwise, let me know what other tweaks may be needed. The check to see if the image is valid is based on the _coordinates object that we already have loaded on the page when the mosaic loads, which it avoids an extra API call to check to see if the image exists or not

**Comment by joefutrelle** [comment]
I think we need that small fix where the image can show next to the mosaic if it's small enough, as before.
