### ISSUE TITLE
unexpected URLs for file downloads

### ISSUE THREAD

**Issue by hsosik** [WHOIGit/ifcbdb#228]
The file download links work on bin pages, but the URLs are not what I expected and the old URL pattern doesn't seem to work. Maybe we have the wrong information entered in the dataset management page, but I can't figure it out. 

For example, I want the hdr file that I expected to be here: http://ifcbdb.whoi.edu:8000/SPIROPA/D20190708T153810_IFCB129.hdr

But that link is dead and instead the file is here: http://ifcbdb.whoi.edu:8000/data/D20190708T153810_IFCB129.hdr

Here is how the dataset management page looks:
![image](https://user-images.githubusercontent.com/12818193/67809846-e01fb900-fa6f-11e9-80ec-7d91b1a9a165.png)

**Comment by joefutrelle** [comment]
@mike-kaimika the `data/...` URL patterns are shadowing the legacy URL patterns. Those URL patterns are problematic because there's nowhere to put them that won't cause shadowing of one set of URLs or the other. We should change the `data/...` URL patterns to something that can be distinguished from the legacy URL patterns, something like `api/data/...`

But there is a design issue here, which is that the timeline could be filtered without a dataset being set. In that case we need to fall back on the "primary dataset" for the bin. The only situation where that wouldn't work would be if there's no dataset at all associated with the bin, in which case we could fall back on the "data" URL pattern.

**Comment by joefutrelle** [comment]
The fix has been pushed to the test server. @hsosik can you confirm that it works now?

**Comment by hsosik** [comment]
Yes, it works. Thanks!
