### ISSUE TITLE
map marker popup vanishes after clustering

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#244]
when you zoom out from the map and the selected bin's marker gets clustered, the popup goes away, and zooming back in doesn't bring it back

**Comment by mike-kaimika** [comment]
I did some initial work on this, but it looks like we may have to go the "hard" route. Once you zoom out, the marker that's supposed to be selected may not be clustered, and that's where the issue is. I tried finding said marked and forcing it to open the popup anyway and it didn't seem to work. I think our solution is going to have to be making sure that the specific marker that needs to be shown is removed from the layer using the clustering, and presents its own layer on the map

This is tricky because it means maintaining a separate layer almost all the time, making sure we put that marker back into the cluster when the  user changes bin (and pull out the new one), etc, so there's likely quite a bit of development to get this one going. At least unless I'm missing some alternative that isn't obvious to me

**Comment by joefutrelle** [comment]
I think we'll need to go the hard route on this. That may have some side benefits too, such as allowing us to draw the selected bin in its location even if it would otherwise be clustered and shown off to the side.

**Comment by mike-kaimika** [comment]
@joefutrelle I think the related issue #295 took care of this one, right?

**Comment by joefutrelle** [comment]
Yes.
