### ISSUE TITLE
Allow dataset ID to be unconstrained for export_metadata

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#360]
Currently the export_metadata endpoint requires a dataset ID to filter by. make this optional.

**Comment by mike-kaimika** [comment]
@joefutrelle I've attached a PR but have some additional questions:

1. I did not see anywhere that actually calls this endpoint from the UI - is it just used externally?
2. By removing that restriction, we are now opening up that call to return everything in the database. Should we add any restrictions to make the user pick some criteria? For instance, require a dataset OR a cruise OR a max start/date range? Limiting just to dataset would have still allowed a lot of data for large datasets, but this change will take it one level further
3. There's a column in the export for the dataset name. This worked before because you were always filtering by one, so we could set that value in each row. Now we can't because if you leave that blank we know the bin, but we don't know which dataset the bin came from (since it could theoretically be part of more than one dataset). I've left that column blank for the time being, but let me know if there's a better way to handle this
4. The filename of the csv was the name of the dataset before. When no dataset is specified, it's now using "metadata.csv" as the file name. We can change this if needed.

Let me know if the PR is good as is, or if tweaks are needed

**Comment by joefutrelle** [comment]
Yeah, there's no UI for this--there probably should be, and we can plan that for a later release.

**Comment by joefutrelle** [comment]
2. Let's set a hard limit on the number of rows and return an error when the limit is exceeded. Not sure what that limit should be but we could start with something fairly large like 500k
3. For a given bin, the dataset or any of more than one dataset it belongs to can be reported in the dataset column. We don't have an efficient representation of a concept of "primary dataset" to rely on but as long as the column identifies one of the datasets the bin belongs to, it's correct
4. some sort of slug made from filtering parameters could be constructed, or we could just stick to something only slightly more specific like `ifcb-metadata.csv`

**Comment by mike-kaimika** [comment]
@joefutrelle I've pushed up additional changes to address those last three items. For #4, I went with just adding "ifcb-" to the begging of the filename to keep it simple

For #3, this got a bit tricky to to handle this within the Django ORM. It currently uses a subquery to pull the first dataset name for a bin, but I'm not sure how performant that will be with the limited data I have in my local setup. If it turns out to be an issue, let me know and I can try to rework it. I'd normally handle that with a CTE (using a row number and limiting it to just row 1), but that seemed to be more complicated to do in the Django ORM and I hadn't gotten it working before switching to the subquery. However, it should still be possible (or we can go to a raw SQL query) if its necessary to get acceptable performance out of this export

Note, this creates a migration, but its for the linking table that already exists, and is marked as not managed, so it doesn't actually make any database changes

**Comment by joefutrelle** [comment]
w/r/t 3, order 100k bins this may very well not perform adequately. Here's a compromise proposal: return a `dataset` column when one is provided as a filtering param, and omit the column otherwise. Users may want that dataset column but this initial compromise may be sufficient until we get a request for it.

**Comment by mike-kaimika** [comment]
The attached PR has been updated to reflect that last request. I think that covers everything on this issue
