### ISSUE TITLE
A user can add the same data directory path multiple times to a dataset

### ISSUE THREAD

**Issue by ethanandrews** [WHOIGit/ifcbdb#411]
When adding a new data directory to a dataset, it's possible to add the same data directory path multiple times, there doesn't seem to be any validation of whether a new data directory already exists. This is the case either through the Django management command, or using the web UI.

<img width="1478" alt="Screenshot 2024-08-29 at 3 06 43 PM" src="https://github.com/user-attachments/assets/5f964db9-b08b-4acc-8456-558127070d14">

**Comment by joefutrelle** [comment]
@mike-kaimika I think the appropriate unique constraint, plus a UI to provide feedback on errors, should do it

**Comment by mike-kaimika** [comment]
This should be all set. The attached PR adds the unique constraint, which handled the UI validation. I also added validation to the management command

**Comment by srstsavage** [comment]
@mike-kaimika @joefutrelle It looks like this constraint prevents the same data directory with different `kind` values from being added multiple times to a dataset (aka `kind` is not included in the unique constraint). Is this intentional? We have our `blobs`, `class_scores`, and `features` co-located in the same parent directory and the current constraint doesn't seem to allow this.

**Comment by joefutrelle** [comment]
@srstsavage this sounds like a new bug, can you open an issue so we can track?
