### ISSUE TITLE
red bar indicating selected bin disappears when changing metric or resolution

### ISSUE THREAD

**Issue by joefutrelle** [WHOIGit/ifcbdb#57]
the nearest bar to the selected bin should be red in the following situations not just immediately after clicking on a bar:

1. hitting the dataset page with a bin selected (i.e., the bin_id query param on the URL is set)
1. after changing metrics
1. after changing resolutions

**Comment by mike-kaimika** [comment]
Initial changes are pushed, but there are two remaining issues
1) There is sometimes a brief delay before the correct bar is highlighted. This is due to the ajax time, and the fix is to put the code to select the in the createTimeSeries, rather than a re-layout after. I will get this completed, but I didn't want it to hold up the rest of the functionality. This is most noticeable when switching metrics
2) Choosing the right bar to highlight is fairly accurate, but there is a chance it will be off by one bar in some cases. This is actually due to how we determine the closest bin, and the fact that the bars may not match up to a bin exactly. The best way to show this is to find a bar and zoom in a bit so its wider. If you click on the left side of it, it might pick one bit, but if you pick on the right side it will select another. The bar get's highlighted on a click correctly because we know which bar was selected, but afterwards, trying to locate the right bar can sometimes be indeterminate

Also, just a note that item #3 in the original comment isn't a factor here; changing bin resolutions does not update the timeline. However, switching bins entirely does (left and right arrows), and that is handled by this last update as well

**Comment by joefutrelle** [comment]
fixed the off by one bar problem

**Comment by mike-kaimika** [comment]
fixed issues with #1
